# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.reportCrashes", true);
user_pref("app.update.backgroundErrors", 2);
user_pref("app.update.custom", "c462f5fd-88c3-46d8-865a-c8a59dfb3036");
user_pref("app.update.lastUpdateTime.background-update-timer", 1392812464);
user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 1392726183);
user_pref("browser.cache.disk.capacity", 39936);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("devtools.eventlooplag.threshold", 100);
user_pref("dom.mms.retrieval_mode", "automatic-home");
user_pref("dom.mozApps.maxLocalId", 1047);
user_pref("dom.mozApps.used", true);
user_pref("gecko.buildID", "20140217160203");
user_pref("gecko.mstone", "30.0a1");
user_pref("general.useragent.updates.lastupdated", "1392726186196");
user_pref("idle.lastDailyNotification", 1392812659);
user_pref("intl.accept_languages", "en-US, en");
user_pref("layers.composer2d.enabled", true);
user_pref("layers.offmainthreadcomposition.log-animations", false);
user_pref("marionette.contentListener", false);
user_pref("marionette.force-local", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.donottrackheader.value", -1);
user_pref("ril.lastKnownSimMcc", "466");
user_pref("ril.mms.mmsc", "http://mms.emome.net:8002");
user_pref("ril.mms.mmsport", 8080);
user_pref("ril.mms.mmsproxy", "10.1.1.1");
user_pref("ril.numRadioInterfaces", 1);
user_pref("ril.radio.disabled", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.telemetry.previousBuildID", "20140217160203");
user_pref('devtools.debugger.forbid-certified-apps', false);
